const {readdirSync} = require('fs')
const docspath = '../docs/'

const files = readdirSync(docspath+process.argv[2])
console.log("---")
console.log("")
console.log("import File from 'docusaurus-file';")
console.log("import {customFields } from '../../docusaurus.config';")
console.log("const repo = customFields.repo")
console.log("")
console.log("## Gyakorlat anyagai")
console.log("")
files.forEach(file=>console.log(`<File filename="${process.argv[2]+"/"+file}" />`))
console.log("")
console.log("---")