name: Update Algolia index

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install JQ
        run: sudo apt install jq
      # Runs a set of commands using the runners shell
      - name: Run Algolia Scraper
        run: docker run -e API_KEY=${{secrets.ALGOLIA_API_KEY}} -e APPLICATION_ID=${{secrets.ALGOLIA_APPLICATION_ID}} -e "CONFIG=$(cat algolia.config.json | jq -r tostring)" algolia/docsearch-scraper
        env:
          API_KEY: ${{secrets.ALGOLIA_API_KEY}}
          APPLICATION_ID: ${{secrets.ALGOLIA_APPLICATION_ID}}
          CONFIG: $(cat algolia.config.json | jq -r tostring)
