name: Push to master

on:
  push:
    branches: [ master ]
    
jobs:
  remove_old:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: sleep 45s
    - name: Remove old deployments
    - run: npx now-clear -n jegyzetek -t ${{ secrets.NOW_TOKEN }}

  update:
    runs-on: ubuntu-latest
    needs: remove_old

    steps:
      - uses: actions/checkout@v2

      - name: Install JQ
        run: sudo apt install jq
      - name: Run Algolia Scraper
        run: docker run -e API_KEY=${{secrets.ALGOLIA_API_KEY}} -e APPLICATION_ID=${{secrets.ALGOLIA_APPLICATION_ID}} -e "CONFIG=$(cat algolia.config.json | jq -r tostring)" algolia/docsearch-scraper